### ISSUE TITLE
Compatibility with micro:bit v2

### ISSUE THREAD

**Issue by microbit-sam** [Tinkertanker/pxt-range-vl53l0x#2]
Hi @tinkertanker,

As you might have seen from microsoft/pxt-microbit#3506 this extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer.

As your extension is currently not building, it will be disabled for micro:bit V2. People attempting to use your extension with a micro:bit V2 board will get error 929. This extension will only be re-enabled on micro:bit V2 once it is fixed.

There are details on how to ensure extensions work on both version of the micro:bit here (lancaster-university/codal-microbit-v2#31).

Looking at your extension source I believe that your extension falls under this category:

> Use of mbed APIs that are not included in the compatibility layer, or microbit-dal APIs that need different constructors

Some I2C compatibility edge cases are still being looked at, and updates will be tracked [here](lancaster-university/codal-microbit-v2#31)

**Comment by dsrc12** [comment]
I can compile with makecode V0 but not V2. This is disappointing as V0 works well. Please update for the latest makecode (as of Apr 21).

**Comment by julien3108** [comment]
Hello

I'm frustrated do not be able to use the ranging extension with Micro:bit. And the comment left by Micro:bitSam is too technical for me (DAL or CODAL !).
Actual I'm working on the ST Time of Flight sensors, I know well the devices driver in the C world but not in the block-based world.

Is there anyway Tinketanker to make the extension work with Micro:bit V2 please ?

I recently used the VL53L0X in the mBot2. It works fantastic well. I hope I can do soon the same thing on the Micro:bit.  

https://www.linkedin.com/posts/julien-nguyen-bb41741b_stmicroelectronics-vl53l0x-timeofflight-activity-6809034076767432704-qRI2

Thank you for your contribution !

Julien Nguyen

**Comment by Mireille-T** [comment]
This issue has been resolved with the latest release of the extension. Thank you! 😄
